version: '3.8'

services:
  mysql-carrental:
    image: mysql:8.0
    container_name: mysql-carrental-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrental
      MYSQL_USER: carrental
      MYSQL_PASSWORD: carrental
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - carrental-network
    restart: unless-stopped

  carrental-backend:
    build:
      context: ./carrental-backend
      dockerfile: Dockerfile.prod
    container_name: carrental-backend-prod
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-carrental:3306/carrental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    depends_on:
      - mysql-carrental
    networks:
      - carrental-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/signup"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  backend_data:
    driver: local
  backend_logs:
    driver: local

networks:
  carrental-network:
    driver: bridge
